const allLocations = [
    // Attractions
    { id: 'sirindhorn-museum', type: 'attraction', name: 'พิพิธภัณฑ์สิรินธร', file: 'sirindhorn-museum.html', image: 'img/img1.jpg', shortDesc: 'ศูนย์วิจัยไดโนเสาร์และพิพิธภัณฑ์ธรณีวิทยาที่สมบูรณ์ที่สุดในอาเซียน', tags: ['ไดโนเสาร์', 'พิพิธภัณฑ์', 'ครอบครัว', 'ความรู้', 'สหัสขันธ์'] },
    { id: 'phra-that-yakhu', type: 'attraction', name: 'พระธาตุยาคู', file: 'phra-that-yakhu.html', image: 'img/img3.jpg', shortDesc: 'เจดีย์สมัยทวารวดีที่ใหญ่ที่สุดในประเทศไทย', tags: ['วัด', 'ประวัติศาสตร์', 'โบราณสถาน', 'วัฒนธรรม', 'กมลาไสย'] },
    { id: 'thepsuda-bridge', type: 'attraction', name: 'สะพานเทพสุดา', file: 'thepsuda-bridge.html', image: 'img/img2.jpg', shortDesc: 'สะพานข้ามน้ำจืดที่ยาวที่สุดในประเทศ ชมวิวสวยงามของเขื่อนลำปาว', tags: ['ธรรมชาติ', 'ชมวิว', 'ถ่ายรูป', 'ริมน้ำ', 'เขื่อนลำปาว'] },
    { id: 'wat-wang-kham', type: 'attraction', name: 'วัดวังคำ', file: 'wat-wang-kham.html', image: 'https://isan.tiewrussia.com/wat_wangkam/images/015.jpg', shortDesc: 'วัดงดงามด้วยสถาปัตยกรรมล้านนาคล้ายวัดเชียงทอง', tags: ['วัด', 'วัฒนธรรม', 'สถาปัตยกรรม', 'ถ่ายรูป', 'เขาวง'] },
    { id: 'phu-po-dinosaur-park', type: 'attraction', name: 'อุทยานไดโนเสาร์ภูโป', file: 'phu-po-dinosaur-park.html', image: 'https://kalasin.city/wp-content/uploads/2022/10/%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A7%E0%B8%81%E0%B8%B2%E0%B8%AC%E0%B8%AA%E0%B8%B4%E0%B8%99%E0%B8%98%E0%B8%B8%E0%B9%8C_%E0%B8%9E%E0%B8%B4%E0%B8%9E%E0%B8%B4%E0%B8%98%E0%B8%A0%E0%B8%B1%E0%B8%93%E0%B8%91%E0%B9%8C%E0%B8%AA%E0%B8%B4%E0%B8%A3%E0%B8%B4%E0%B8%99%E0%B8%98%E0%B8%A3-05-600x400.jpg', shortDesc: 'แหล่งค้นพบรอยตีนไดโนเสาร์ที่ชัดเจนที่สุดแห่งหนึ่งของไทย', tags: ['ไดโนเสาร์', 'ธรรมชาติ', 'เดินป่า', 'ครอบครัว'] },
    { id: 'phrae-wa-silk-village', type: 'attraction', name: 'หมู่บ้านทอผ้าไหมแพรวา', file: 'phrae-wa-silk-village.html', image: 'https://do.lnwfile.com/_/do/_raw/jz/xq/w8.png', shortDesc: 'แหล่งกำเนิดของ "แพรวา ราชินีแห่งไหม" ผ้าไหมทอมือลายโบราณ', tags: ['วัฒนธรรม', 'ผ้าไหม', 'หมู่บ้าน', 'ของฝาก', 'คำม่วง'] },
    { id: 'dok-ket-beach', type: 'attraction', name: 'หาดดอกเกด', file: 'dok-ket-beach.html', image: 'https://static.thairath.co.th/media/dFQROr7oWzulq5FZUEh9wz24CHp4UkHzETUB201n2tMcL1ETeVuv2j12dDjeRWjK17A.webp', shortDesc: '"ทะเลอีสาน" ที่ชาวกาฬสินธุ์นิยมมาพักผ่อน มีกิจกรรมทางน้ำมากมาย', tags: ['ธรรมชาติ', 'พักผ่อน', 'ครอบครัว', 'ริมน้ำ', 'กิจกรรม', 'เขื่อนลำปาว'] },
    { id: 'pha-sawoei-viewpoint', type: 'attraction', name: 'ผาเสวย', file: 'pha-sawoei-viewpoint.html', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPfVXnEuTX5zSdG4_4PJr9EvxNHLVaQJtx5g&s', shortDesc: 'จุดชมวิวบนเทือกเขาภูพาน รอยต่อระหว่างกาฬสินธุ์และสกลนคร', tags: ['ธรรมชาติ', 'ชมวิว', 'ภูเขา', 'ถ่ายรูป', 'ภูพาน'] },
    { id: 'wat-phutthanimit', type: 'attraction', name: 'วัดพุทธนิมิต (ภูค่าว)', file: 'wat-phutthanimit.html', image: 'https://mpics.mgronline.com/pics/Images/561000004305306.JPEG', shortDesc: 'วัดเก่าแก่ที่ประดิษฐานพระพุทธไสยาสน์แกะสลักบนแผ่นผา', tags: ['วัด', 'ประวัติศาสตร์', 'โบราณสถาน', 'ชมวิว', 'สหัสขันธ์'] },

    // Restaurants
    { id: 'ploen-kalasin', type: 'restaurant', name: 'เพลิน กาฬสินธุ์', file: 'ploen-kalasin.html', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdCgLyrMwpNLt7OiS7AM7aKSvnp9r0A018Dw&s', shortDesc: 'ร้านอาหารบรรยากาศดี มีดนตรีสด พร้อมเมนูหลากหลายใจกลางเมือง', tags: ['ร้านอาหาร', 'กลางคืน', 'ในเมือง'] },
    { id: 'somtum-sam-pee-nong', type: 'restaurant', name: 'ส้มตำสามพี่น้อง', file: 'somtum-sam-pee-nong.html', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsJF_1wgWeZ-CA2foIR_VjorrXHKC6FOzkvw&s', shortDesc: 'ร้านส้มตำชื่อดัง รสชาติจัดจ้าน ถูกใจคนท้องถิ่นและนักท่องเที่ยว', tags: ['ร้านอาหาร', 'อาหารอีสาน', 'ส้มตำ', 'รสจัด'] },
    { id: 'berler-shabu', type: 'restaurant', name: 'เบ้อเร่อ ชาบูพันธุ์แท้', file: 'berler-shabu.html', image: 'https://lh3.googleusercontent.com/gps-cs-s/AC9h4nozZ7gRoEiLor--_OfHjPdXCm-KdQA6fQzKqoC8Ma4mu0YnPEUaK7TlT4gxnqJ-5j57B4isAMinT8BaQJMloXKRB9CWEqTmRLWSGrF9J24zY7grj-Rr-WPcW6a_AUoGR2OZNBY=w408-h408-k-no', shortDesc: 'บุฟเฟ่ต์ชาบูและปิ้งย่างชื่อดัง ไลน์อาหารจัดเต็ม', tags: ['ร้านอาหาร', 'บุฟเฟ่ต์', 'ชาบู', 'ปิ้งย่าง'] },
    { id: 'the-loft-cafe', type: 'restaurant', name: 'The Loft Cafe Kalasin', file: 'the-loft-cafe.html', image: 'https://img.wongnai.com/p/400x0/2021/04/03/14e929371923466390d70cb05c8df921.jpg', shortDesc: 'คาเฟ่สไตล์ลอฟท์ใจกลางเมือง บรรยากาศเท่ๆ ดิบๆ สำหรับคอกาแฟ', tags: ['คาเฟ่', 'กาแฟ', 'ในเมือง', 'ถ่ายรูป'] },
    { id: 'suk-plai-na-cafe', type: 'restaurant', name: 'สุขปลายนา คาเฟ่', file: 'suk-plai-na-cafe.html', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeeWQuEaVoi1MQzGKIfBIARfRrqamRFg1amw&s', shortDesc: 'คาเฟ่กลางทุ่งนา บรรยากาศร่มรื่น สบายตา เหมาะแก่การพักผ่อน', tags: ['คาเฟ่', 'กาแฟ', 'ธรรมชาติ', 'ถ่ายรูป', 'ร้านอาหาร'] },
    { id: 'pingfai-kalasin', type: 'restaurant', name: 'ร้านอาหารพิงไฟ', file: 'pingfai-kalasin.html', image: 'https://lh3.googleusercontent.com/gps-cs-s/AC9h4np7817Hc6HbDWTCWgtOxmYbzyobHyLSBFtQTyYMONiLrcUqX1Sb4KRcxOxYnCXxCbPBcRJ0eDTkwdRhLvNui63BmaBOJB2sC_k9kPac4dg2N2OM-uKAdoow6LGUwQkfhUPc8VEc-Q=w408-h544-k-no', shortDesc: 'ร้านอาหารบรรยากาศดี มีเมนูหลากหลาย ทั้งอาหารไทยและอีสาน', tags: ['ร้านอาหาร', 'อาหารไทย', 'อาหารอีสาน', 'ครอบครัว'] },

    // Accommodations
    { id: 'Suphak', type: 'accommodation', name: 'โรงแรมสุภัค', file: 'Suphak.html', image: 'https://images.trvl-media.com/lodging/17000000/16760000/16758500/16758416/4b3ad5f7.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill" alt="Gallery image 3', shortDesc: 'ที่พักสะอาด ราคาเป็นมิตร ใกล้สถานีขนส่งกาฬสินธุ์', tags: ['ที่พัก', 'โรงแรม', 'ในเมือง', 'ราคาประหยัด'] },
    { id: 'ratchapruek-resort', type: 'accommodation', name: 'ราชพฤกษ์ รีสอร์ท', file: 'Ratchapreuk.html', image: 'https://www.chuwab.com/images/hotel/1/12/3712/bimg_20160602111811.jpg', shortDesc: 'รีสอร์ทบรรยากาศเงียบสงบ เหมาะสำหรับการพักผ่อน', tags: ['ที่พัก', 'รีสอร์ท', 'พักผ่อน'] },
    { id: 'qubix-hotel', type: 'accommodation', name: 'โรงแรม คิวบิส เดอะ เบส กาฬสินธุ์', file: 'q-bis-the-base-kalasin.html', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStukjW36CXkc06NxY4XeV9xyDePzQ1uDtA4Q&s', shortDesc: 'โรงแรมทันสมัยใจกลางเมืองกาฬสินธุ์ พร้อมสิ่งอำนวยความสะดวกครบครัน', tags: ['ที่พัก', 'โรงแรม', 'ทันสมัย', 'ในเมือง'] },
    { id: 'dino-studio-hotel', type: 'accommodation', name: 'โรงแรมดิโน่ สตูดิโอ', file: 'dino-inn-hotel.html', image: 'https://pix10.agoda.net/hotelImages/877/877029/877029_15082510150034980462.jpg?ca=5&ce=1&s=414x232', shortDesc: 'โรงแรมราคาประหยัด ตั้งอยู่ในทำเลดี เดินทางสะดวก ห้องพักสะอาด', tags: ['ที่พัก', 'โรงแรม', 'ไดโนเสาร์'] },
    { id: 'Rimpao', type: 'accommodation', name: 'โรงแรมริมปาว', file: 'Rimpao.html', image: 'https://images.trvl-media.com/lodging/17000000/16760000/16759900/16759859/398e68f2.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill', shortDesc: 'โรงแรมมาตรฐานใจกลางเมือง เดินทางสะดวกสบาย', tags: ['ที่พัก', 'โรงแรม', 'ในเมือง', 'ครอบครัว'] }
];